### Recuperar todas libreta por nombre
GET http://localhost:1234/productos/libreta

### Recuperar una película por id
GET http://localhost:1234/productos/categoria/672d01d89ad2ddcdfed618bf


### Borrado logico una película por id
DELETE http://localhost:1234/proveedores/673a070e8740b8f278ca2ba0

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=action

### Crear una película con POST
POST http://localhost:1234/pedidos
Content-Type: application/json

{
  "fecha_llegada_envio": "2023-10-10T12:00:00Z",
  "estado": "pendiente",
  "tipo_pedido": "envio",
  "socio_empresa_id": "673a070e8740b8f278ca2ba0",
  "productos": [
    {
      "producto_id": "6738db03821c5cbf7b62a1d2",
      "cantidad": 2
    },
    {
      "producto_id": "6738da60821c5cbf7b62a1cd",
      "cantidad": 1
    }
  ]
}


### Crear una película con POST
POST http://localhost:1234/usuarios
Content-Type: application/json

{"nombre": "america",
  "email":  "america@gmail.com",
  "contraseña": "contrasena123",
  "tipo": "empleado"
}

### Actualizar una película
PATCH http://localhost:1234/productos/6738da60821c5cbf7b62a1cd
Content-Type: application/json

{
  "nombre": "lapiz",
  "descripcion": "producto editado"
}

