### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/671a6653b67e477ac7d7b13c

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=action

### Crear una película con POST
POST http://localhost:1234/empresas
Content-Type: application/json

{
  "nombre": "3TEST ENTERPRISE3",
  "correo": "3test@test3"
}

### Actualizar una película
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2022
}