### Recuperar todas las películas
GET http://localhost:1234/categorias

### Recuperar una película por id
GET http://localhost:1234/categorias/671b089f45311c0bf7e63fff

### Borrado logico una película por id
DELETE http://localhost:1234/categorias/671b089f45311c0bf7e63fff

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=action

### Crear una película con POST
POST http://localhost:1234/categorias
Content-Type: application/json

{
  "nombre": "Telas avanzadas",
  "descripcion": "telas de todo tipo avanzadas"
}

### Actualizar una película
PATCH http://localhost:1234/categorias/671c54be98cb67227de8975f
Content-Type: application/json

{
  "descripcion": "TELAS"
}